export const CORE_VERSION = '0.1.0';
export * from './ids.js';
export * from './domain/schemas.js';
export * from './domain/maintenance.js';
export * from './repo/keys.js';
export type { Repository } from './repo/repository.js';
export { createMemoryRepository } from './repo/memory.js';
export { createDynamoRepository } from './repo/dynamo.js';
export { ensureTable } from './repo/table.js';
export { SEED_APPLIANCES, seedRepository } from './seed/household.js';
